theme: jekyll-theme-architect
# Site settings
title: BY Blog
SEOTitle: 柏荧的博客 | BY Blog
header-img: img/post-bg-desk.jpg
email: lvpeng@herenit.com
description: "Every failure is leading towards success."
keyword: "BY, BY Blog, 柏荧的博客, darksolong, 邱柏荧, iOS, Apple, iPhone"
url: "http://DarkSoLong.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/DarkSoLong/DarkSoLong.github.io.git" # you code repository
